name: Releases

on: 
  push:
    tag:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "pcatt/greedy_builder.cpp, requirements.txt, setup.py, README.md, LICENSE"
        bodyFile: "README.md"
        tag: $GITHUB_REF_NAME